### ISSUE TITLE
Increase font size for menu items

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/static-website#101]
Now that there are fewer menu items I think we should increase the font size as it is quite small on a large monitor

**Comment by jeffbrown** [comment]
The menu has changed since this issue was filed.  @graemerocher Do you think the current font should be larger?

Thanks.

**Comment by jeffbrown** [comment]
@graemerocher Do you have concerns about the font size on the current site?

**Comment by graemerocher** [comment]
no looks good to me. thanks
