### ISSUE TITLE
Logo missing on Firefox

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/static-website#114]
The logo is gone from the top left of https://micronaut.io/

Is this intentional?

**Comment by jeffbrown** [comment]
I am currently seeing the logo.  Will investigate.

**Comment by JasonTypesCodes** [comment]
We were swapping logos yesterday.  If you refresh now, it should show.  Please let us know if you still don't see it.

**Comment by graemerocher** [comment]
Weird I see it on Chrome and Safari but not on Firefox, tried refreshing the cache

**Comment by graemerocher** [comment]
deleted all browsing history and still not there on Firefox

**Comment by graemerocher** [comment]
@jameskleeh and @alvarosanchez also cannot see the logo on Firefox

**Comment by graemerocher** [comment]
<img width="1451" alt="Screenshot 2020-07-29 at 17 33 33" src="https://user-images.githubusercontent.com/66626/88820477-a710a280-d1c1-11ea-8a71-4be1c18c0c4e.png">

**Comment by sdelamo** [comment]
@graemerocher could you confirm this is fixed for you now?

**Comment by graemerocher** [comment]
Yes it is fine now
