### ISSUE TITLE
Micronaut IoT Case Study (SmartThings)

### ISSUE THREAD

**Issue by kroegerk** [micronaut-projects/static-website#134]
write brief description and link to case study on OCI site

https://objectcomputing.com/case-studies/case-study-from-monolith-to-microservices-with-micronaut

**Comment by jeffbrown** [comment]
> write brief description and link to case study on OCI site

@kroegerk How brief would you like?

We can start with this:

> A large, consumer-facing IoT device network that relied upon a monolithic architecture found that the network struggled to keep pace with increasing demand. In response, the team built a lightweight microservices system using the Micronaut framework, which provided the smooth learning curve, extensibility, speed, testing ease, and scalability necessary to better serve its growing customer base.

**Comment by kroegerk** [comment]
Oh! I had completely forgotten I put that in there. I was thinking of something more casual and personal for the blog. I can start a doc and share it with you and the team for input. Hold please ...

**Comment by kroegerk** [comment]
Google Doc shared. https://docs.google.com/document/d/1SxVQ6EIiOn208nz6VCKg49jdqi1CDc4Z-EGLs74KWSo/edit?usp=sharing
