### ISSUE TITLE
Blog about Webinar : MICRONAUT® 2: LAUNCHING THE TECHNOLOGY OF THE FUTURE

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/static-website#137]
https://objectcomputing.com/products/micronaut/resources/micronaut-2-webinar

**Comment by kroegerk** [comment]
This will be ready once I have links to the slide deck and the video.

https://github.com/micronaut-projects/static-website-private/blob/master/posts/2020-08-21-micronaut-2-qa-session.md
