### ISSUE TITLE
Support Multiple language choice in home page code samples

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/static-website#14]
<img width="466" alt="spreadsheet_builder" src="https://user-images.githubusercontent.com/864788/42226473-5299290c-7edf-11e8-8f7f-d83ea64a45fd.png">

**Comment by sdelamo** [comment]
If you change one code sample, it should change them all. Maybe even store a cookie.

**Comment by jeffbrown** [comment]
> Support Multiple language choice in home page code samples

We have this setup in the user guide.  Is this issue specifically to add that to the micronaut.io home page?

**Comment by JasonTypesCodes** [comment]
Let's close this for now.  We may revisit this in the near future after some pending changes are made to the site content and style
