### ISSUE TITLE
vertical scrollbar on nav header.

### ISSUE THREAD

**Issue by Yogendra0Sharma** [micronaut-projects/static-website#140]
Vertical Scrollbar showing on navigation header.
![isue](https://user-images.githubusercontent.com/1375860/91156181-700aaf80-e6e1-11ea-9280-46f1930951e0.PNG)

Expected Result:- 
The header should not contain any scrollbar.

Please assign this issue to me.

**Comment by sdelamo** [comment]
which browser and os are you using ? Is it chrome ?

**Comment by Yogendra0Sharma** [comment]
> which browser and operating system are you using ? Is it chrome ?

OS: Windows 10 64bit
Browser: Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by sdelamo** [comment]
I managed to reproduce when I set zoom to 90% in chrome. I don't get it at 100%.
