### ISSUE TITLE
Set up HTTPS properly

### ISSUE THREAD

**Issue by brunoborges** [micronaut-projects/static-website#18]
Currently the website is on http://micronaut.io.

If accessed through `https`at https://micronaut.io, it shows the invalid GitHub certificate and the website is considered insecure.

**Comment by sdelamo** [comment]
Micronaut website is now available over `https`. Static resources are all pointing to `https` a well. 

See: https://github.com/micronaut-projects/static-website/commit/82475f81e8c0a5782515492909691019d3a7c148
