### ISSUE TITLE
Update Google Cloud logo and add Oracle Cloud logo

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/static-website#195]
On https://micronaut.io the Google Cloud logo is out of date with the latest design and the Oracle Cloud logo is missing.

Would also consider removing Netflix Eureka which is now largely deprecated (along with most of Netflix OSS)

**Comment by jeffbrown** [comment]
We have some other design work in progress around the main page.  We will account for this as that design work progresses.

FYI... Guillaume LaForge from Google suggests we use https://cloud.google.com/images/velostrata/cloud-lockup-logo.png for their logo.

**Comment by jeffbrown** [comment]
The current page design for the micronaut.io home page (design not published to the web site yet) has removed these logos and the associated cloud image.

I think we should consider a page that summarizes cloud provider integrations.

**Comment by graemerocher** [comment]
@jeffbrown any update on this? I see an update in that the Azure logo has been added but still no Oracle Cloud

**Comment by wiesej** [comment]
The logos have been updated on the new site. 
<img width="1175" alt="Screen Shot 2021-03-18 at 1 21 30 PM (1)" src="https://user-images.githubusercontent.com/25908525/111677623-649de380-87ed-11eb-88e9-dbcd74853bf5.png">
