### ISSUE TITLE
Broken Link In Guide

### ISSUE THREAD

**Issue by jeffbrown** [micronaut-projects/static-website#206]
The **_Copy To Clipboard_** image at https://guides.micronaut.io/mn-application-aws-lambda-graalvm/guide/index.html points to https://guides.micronaut.io/mn-application-aws-lambda-graalvm/img/clippy.svg which does not exist.

**Comment by JasonTypesCodes** [comment]
This has been resolved. See: https://github.com/micronaut-projects/micronaut-guides/commit/f394aec43499b2e4ad635b1283eacb832953ebe4
