### ISSUE TITLE
Binary Download Link

### ISSUE THREAD

**Issue by jeffscottbrown** [micronaut-projects/static-website#219]
The Binary download link at [micronaut.io/download/](https://micronaut.io/download/) currently links to a .zip of the Git repo.  Instead it should point to the `cli` binary, like [github.com/micronaut-projects/micronaut-starter/releases/download/v2.4.1/micronaut-cli-2.4.1.zip](https://github.com/micronaut-projects/micronaut-starter/releases/download/v2.4.1/micronaut-cli-2.4.1.zip).

**Comment by JasonTypesCodes** [comment]
The binary download link now points to the CLI zip
