### ISSUE TITLE
Fix Module Doc Links

### ISSUE THREAD

**Issue by jeffscottbrown** [micronaut-projects/static-website#220]
Several of the modules at https://micronaut.io/docs/ have links that point to a README instead of the module documentation.

@sdelamo provided the following list of correct links and suggested if the module does not have a latest doc, then replace latest with snapshot:

https://micronaut-projects.github.io/micronaut-groovy/latest/guide
https://micronaut-projects.github.io/micronaut-kotlin/latest/guide
https://micronaut-projects.github.io/micronaut-jms/latest/guide
https://micronaut-projects.github.io/micronaut-kafka/latest/guide
https://micronaut-projects.github.io/micronaut-mqtt/latest/guide
https://micronaut-projects.github.io/micronaut-nats/latest/guide
https://micronaut-projects.github.io/micronaut-rabbitmq/latest/guide
https://micronaut-projects.github.io/micronaut-acme/latest/guide
https://micronaut-projects.github.io/micronaut-cache/latest/guide
https://micronaut-projects.github.io/micronaut-hibernate-validator/latest/guide
https://micronaut-projects.github.io/micronaut-ignite/latest/guide
https://micronaut-projects.github.io/micronaut-picocli/latest/guide
https://micronaut-projects.github.io/micronaut-security/latest/guide
https://micronaut-projects.github.io/micronaut-test/latest/guide
https://micronaut-projects.github.io/micronaut-reactor/latest/guide
https://micronaut-projects.github.io/micronaut-rxjava1/latest/guide
https://micronaut-projects.github.io/micronaut-rxjava3/latest/guide
https://micronaut-projects.github.io/micronaut-multitenancy/latest/guide
https://micronaut-projects.github.io/micronaut-rss/latest/guide
https://micronaut-projects.github.io/micronaut-views/latest/guide

**Comment by ilopmar** [comment]
In the old website we have a way to flag a module as a snapshot or not so the link to the docs is `snapshot` instead of `latest`: https://github.com/micronaut-projects/static-website/blob/master/conf/modules.yml#L14
