### ISSUE TITLE
Missing current version of Micronaut in doc

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/static-website#223]
The current [documentation main page](https://micronaut.io/docs/) doesn't show the current Micronaut version. The dropdown is empty but it should be 2.4.1:

![versions](https://user-images.githubusercontent.com/559192/111963760-29a0f600-8af4-11eb-9bb4-7f62d66a9ff6.jpg)

**Comment by graemerocher** [comment]
Isn't this by design since it is not an older version?

**Comment by ilopmar** [comment]
Not sure, but it feels weird to see the dropdown empty.

**Comment by JasonTypesCodes** [comment]
This is intentional
