### ISSUE TITLE
UI enhancement: light mode  

### ISSUE THREAD

**Issue by ans1genie** [micronaut-projects/static-website#227]
The dark mode is good and compatible with headers, 
but for light mode, the header stay black as default. would be great to fully support a light mode :D

**Comment by JasonTypesCodes** [comment]
Are you referring to the Launch page? https://micronaut.io/launch/ ?

**Comment by JasonTypesCodes** [comment]
I'm not sure what you mean by "compatible with headers"

**Comment by ans1genie** [comment]
Oh! yes, sorry. 
I was on the https://docs.micronaut.io/latest/guide/ 
The headers on darkmode:
![image](https://user-images.githubusercontent.com/16513804/130121709-0b0cc7de-ecf7-4efb-9452-5e03700e8aac.png)

on light mode stays the same:
![image](https://user-images.githubusercontent.com/16513804/130121770-0a3591d8-cbcc-4c64-9495-9c3c4e7e3731.png)

**Comment by JasonTypesCodes** [comment]
Thanks for the feedback :)

I reviewed this with our design team and, for the time, we will be maintaining the current design.
