### ISSUE TITLE
Add Windows install instruction using scoop

### ISSUE THREAD

**Issue by cyparu** [micronaut-projects/static-website#26]
Starting with [v1.0.4](https://github.com/lukesampson/scoop/pull/3183), Micronaut can easily be installed/updated on Windows [Scoop](https://scoop.sh)
The download/install documentation page (https://micronaut.io/download.html) may include install & update scoop commands
```cmd
X:\> :: freshly install the latest version of micronaut
X:\> scoop install micronaut
X:\> :: update micronaut to latest version (if already installed)
X:\> scoop update micronaut
X:\> :: switch micronaut to a selected/pre-installed version
X:\> scoop reset micronaut@1.0.4

```

**Comment by sdelamo** [comment]
I think it makes more sense to add this as an entry of the install sections in the main documentation: https://docs.micronaut.io/latest/guide/index.html
