### ISSUE TITLE
Dead link in latest guides

### ISSUE THREAD

**Issue by aytdm** [micronaut-projects/static-website#31]
Hi, thank you for your documentation! I found a dead link on `SECURE A MICRONAUT APP WITH GITHUB` in the [latest guides](https://guides.micronaut.io/). 

<img src="https://user-images.githubusercontent.com/31028259/75109639-7a7fba00-5668-11ea-9895-87aa42a662e0.png" width="400">

It's occured due to wrong project name. That correct project name is `micronaut-oauth2-github` but the project name written in [guides.json](https://raw.githubusercontent.com/micronaut-projects/micronaut-guides/gh-pages/guides.json) is `micronaut-github`. I'm not sure how to fix it, so I create new issue.

I would appreciate if you could fix at your convenience.

**Comment by sdelamo** [comment]
Thanks for reporting @aytdm

**Comment by aytdm** [comment]
Thank you for the quick fix :)
