### ISSUE TITLE
Making module naming consistent in documentation

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/static-website#73]
On https://micronaut.io/documentation.html

We sometimes refer to "Micronaut XXX" (most common), sometimes "XXX Configuration" (for example "Neo4j Configuration") and sometimes just "XXX" (for example "Picocli")

For consistency we should standardize. Either all should be called "Micronaut XXX", all "XXX" or all "XXX Configuration"

**Comment by graemerocher** [comment]
My personal vote is just to use "XXX" and drop the "Micronaut" prefix and "Configuration" suffix

**Comment by sdelamo** [comment]
I've set to "Micronaut XXX".
